export enum ErrorCode {
  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',

  // Orders
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',

  // Batch
  BATCH_NOT_FOUND = 'BATCH_NOT_FOUND',

  // Couriers
  UNKNOWN_COURIER = 'UNKNOWN_COURIER',
  COURIER_CLIENT_ERROR = 'COURIER_CLIENT_ERROR',
  COURIER_UNAVAILABLE = 'COURIER_UNAVAILABLE',
  COURIER_AUTH_FAILED = 'COURIER_AUTH_FAILED',
  COURIER_NOT_ACTIVE = 'COURIER_NOT_ACTIVE',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Internal
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export const HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
  [ErrorCode.TOKEN_INVALID]: 401,
  [ErrorCode.ORDER_NOT_FOUND]: 404,
  [ErrorCode.DUPLICATE_ORDER]: 409,
  [ErrorCode.BATCH_NOT_FOUND]: 404,
  [ErrorCode.UNKNOWN_COURIER]: 400,
  [ErrorCode.COURIER_CLIENT_ERROR]: 422,
  [ErrorCode.COURIER_UNAVAILABLE]: 502,
  [ErrorCode.COURIER_AUTH_FAILED]: 502,
  [ErrorCode.COURIER_NOT_ACTIVE]: 400,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,
};
